### ISSUE TITLE
Plugin not working for NetBeans 12.6

### ISSUE THREAD

**Issue by Chris2011** [haidubogdan/netbeans-php-blade-plugin#1]
I wanted to install your plugin in NetBeans 12.6 and I got this error: 
<img width="401" alt="image" src="https://user-images.githubusercontent.com/795658/147223327-f9fc691b-d267-4537-a355-b11fd8f5d573.png">

And as you can see, the scrollbar is long, but I think those errors are the same. So this plugin is not working for NetBeans 12.6. I see that you already had problems to support each new version which is very simple. Build your plugin with the most minimal/oldest version where your plugin should work up on. So if you want to support 12.0, 12.1, 12.2....12.6, 13, you just need to build it for 12.0 and it will work to the latest, if you don't use a specific API which will change etc. But this will work afaik.

**Comment by haidubogdan** [comment]
Hi Chrizzly,
Yes the version 12.6 is quite recent so I didn't create a npm file for it.
I will update the branch and add a npm for the newest netbeans version.
I'm also working on the version v2.0.0 which will have indexing so it will
have autocomplete for blade files and yields.

Bogdan

**Comment by haidubogdan** [comment]
I've updated the branch to have compatiblity for netbeans 12.6 . The nbm file is located in the nbm folder.

**Comment by Chris2011** [comment]
Hey Bogdan, as I mentioned it earlier, you don't need to build a new version for every new NetBeans version, this is also fatal, if I need to wait for your update for NetBeans 13. I can say, what I do with my plugins. I build my plugins with JDK 9 or 11 and build it with the oldest platform that I want to support. Most of the stuff can be handled >= NetBeans 9.0 RELEASE 90. If not, like for the LSP which came in 11.0 or 11.1 and later I need to make it for this. So if you want to support as much versions of NetBeans as possible, use the oldest one where your plugin will still work. It doesn't need to work with NetBeans 9.0 but if you want from 12.0 on, download that version, add it to the platform and it will work >= 12.0.

Also please come and join our slack chan so we  https://netbeans.slack.com/ so we can talk there about NetBeans related stuff. And what I think would be good, please activate the discussion section of your plugin, so that we can create discussions instead of tickets :).

**Comment by Chris2011** [comment]
Also, if you build it for just one version like 12.0 up front, you just need one nbm file, not 6 :).

**Comment by haidubogdan** [comment]
ah ... I had a experience when this didn't work. Maybe it was due to wrong
implementation version :).
Thanks for the info,
Bogdan

**Comment by Chris2011** [comment]
Yes, could be. It depends of what APIs you need to work with.

**Comment by Chris2011** [comment]
It is working now, thx.
