### ISSUE TITLE
Blade Sintax Error, Unexpected End of File, Expected T_BLADE_STOP

### ISSUE THREAD

**Issue by systemsolutionweb** [haidubogdan/netbeans-php-blade-plugin#10]
**Blade Sintax Error
Unexpected End of File
Expected T_BLADE_STOP**

You get that exception if you do
```blade
@section('modals')
   <!--contents-->
@append
```
`@append` is also a close tag for `@section` but it is not supported, 
i think also `@show`,`@stop` are closing tags for `@section` too
for `@section` `@parent` directive is missing

There is a lot mising basic blade directives like 
`@method`,
`@can`,`@endcan`,
`@canany`,`@endcanany`,
`@while`,
`@error`,
`@hasSection`,
`@sectionMissing`,
`@checked`,
`@includeWhen`,
`@includeUnless`,
`@includeFirst`,
`@each`,
`@once`,
`@pushOnce`
and more

**Comment by haidubogdan** [comment]
Hi,
yes some blade directives are not implemented, and I didn't know about append.
I've done a new release on https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb122-126-04032022 where the append tag is recognized as a closing tag. The (@stop and @show) are already added as a closing tag for @section.
For the moment I think I will add some logic related to all these blade directives for later.
Also, a version and deprecation system is also required to keep this in balance.

**Comment by systemsolutionweb** [comment]
Thanks, it is fixed now
>For the moment I think I will add some logic related to all these blade directives for later.

I will be waiting for new releases 👍

**Comment by systemsolutionweb** [comment]
`@can`,`@elsecan`,`@endcan`,
`@cannot`,`@elsecannot`,`@endcannot`
`@canany`,`@elsecanany`,`@endcanany`,
`@switch`, `@case`, `@default`, `@endswitch`
`@while`,`@endwhile`,
`@empty` for `@forelse `
Those are the most important, 

Examples:
```blade
@can('update')
    <!-- The current user can update the post... -->
@elsecan('create')
    <!-- The current user can create new posts... -->
@else
    <!-- ... -->
@endcan


@canany(['update', 'view', 'delete'])
    <!-- The current user can update, view, or delete the post... -->
@elsecanany(['create'])
    <!-- The current user can create a post... -->
@endcanany

 
@cannot('update')
    <!-- The current user cannot update the post... -->
@elsecannot('create')
    <!-- The current user cannot create new posts... -->
@endcannot


@forelse ($users as $user)
    <li>{{ $user->name }}</li>
@empty
    <p>No users</p>
@endforelse
 

@while (true)
    <p>I'm looping forever.</p>
@endwhile


@switch($i)
    @case(1)
        First case...
        @break
 
    @case(2)
        Second case...
        @break
 
    @default
        Default case...
@endswitch
```

**Comment by systemsolutionweb** [comment]
@haidubogdan hi, is `@append` bug back?

```blade
@section('modals')
   <!--contents-->
@append
```

**Comment by haidubogdan** [comment]
Hi, 
sorry for the regression.
`@append` is a bit elusive in the laravel documentation.

With this occasion I noticed that `@can` and it's derivatives was not handled also, so I added a quick fix for them in the latest release,

Thank you :).

**Comment by systemsolutionweb** [comment]
It's working again, thanks
