### ISSUE TITLE
Plugin breaks Javascript comments

### ISSUE THREAD

**Issue by erikn69** [haidubogdan/netbeans-php-blade-plugin#11]
Discussed on https://github.com/haidubogdan/netbeans-php-blade-plugin/issues/3#issuecomment-1057066344

Expected
```html
<script>
function test(){
    //test
}
</script>
```
Blade Plugin
![image](https://user-images.githubusercontent.com/4933954/156816033-8e226c81-17ab-4b1c-8507-54b565b0081f.png)

After that it breaks other js highlight sintax

**Comment by haidubogdan** [comment]
Hi I created a new release to fix this : 
It was an embedding issue with new lines
https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb122-126-05032022a

**Comment by erikn69** [comment]
Looks great, thanks for your time
