### ISSUE TITLE
Blade Sintax Error Unexpected String, `@extends`,`@yield` needs extra support

### ISSUE THREAD

**Issue by systemsolutionweb** [haidubogdan/netbeans-php-blade-plugin#12]
Suppose you have this
```php
<?php
$string='string';
function getString(){
   return 'string';
}
?>
```
Now try this
```blade
@extends(getString())
or
@extends($string)

@yield(getString())
or
@yield($string)
```
That works on laravel but this plugin give me
**Blade Sintax Error**
**Unexpected:** String
**After:** )

Maybe trying other things also, for example
```blade
@include(($condition?'test1':'test2').'.blade_file')
```
If you have html/js with an `@` it fails too, try this and look at the error
```html
<script>
// @ (
</script>
<script>
// @ ''(
</script>
```

**Comment by haidubogdan** [comment]
I've started with @include and @extends to not throw parse exception for expression in
https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb122-126-05032022a

**Comment by systemsolutionweb** [comment]
> https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb122-126-05032022a

It's working now on `@include` and `@extends`

```html
<script>
// @ (
</script>
<script>
// @ ''(
</script>
```
On  those examples still fails, but it doesn't matter, i could avoid using `@` when it isn't a directive

**Comment by systemsolutionweb** [comment]
@haidubogdan also try this
```blade
@section('content')
  <td style="mso-number-format:&#39;@&#39;;"></td>
@endsection
```
**Blade Sintax Error**
**Unexpected:** End of File
**Expected:** T_BLADE_COMMENT, T_BLADE_STOP
