### ISSUE TITLE
Plugin Breaks how JS works

### ISSUE THREAD

**Issue by angeljqv** [haidubogdan/netbeans-php-blade-plugin#15]
Suppose you have
```html
<script>
var myVar={key:[]};
myVar.key.length;
</script>
```
With this plugin when you double click on `length`, all the line gets selected
![image](https://user-images.githubusercontent.com/79208641/157086505-b6e1d2ab-8e07-4c97-b516-2d470b7403e8.png)
Without this plugin when you double click on `length`, only `length` gets selected
![image](https://user-images.githubusercontent.com/79208641/157086612-80ae52ca-a398-41fa-956c-595425360481.png)

**Comment by haidubogdan** [comment]
Hi, yes this was done to enable full highlight of blade views paths.
As this is mainly a netbeans core library issue, I will either have to use a switch option or create some custom code to replace this core library functionality.

**Comment by parallels999** [comment]
Also notice this, it's annoying, I am deleting variable names by mistake because of this

**Comment by haidubogdan** [comment]
Hi 
I've found a compromise for **javascript properties** and **blade paths** highlight in this release
[release 19 08 2022](https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb-122-126-19082022)

**Comment by angeljqv** [comment]
It seems to work, thank you very much
