### ISSUE TITLE
Blade Sintax Error on CSS

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#18]
Example:
```blade
<style>
@-webkit-keyframes swal2-toast-show{
    0% { transform : translateY(-.625em) }
    100%{ transform : translateY(0) }
}
</style>
```
I get
`Blade Sintax Error Unexpected  )  after variable 'translateY' `
![image](https://user-images.githubusercontent.com/109294935/185167241-63eb4854-b1ab-4b6d-b3d2-7d86d9139d51.png)

**Comment by cesarreyes3** [comment]
+1

**Comment by haidubogdan** [comment]
I added a fix for this parser error on : [https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb-122-126-07092022](https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb-122-126-07092022 )

**Comment by parallels999** [comment]
@haidubogdan thanks
