### ISSUE TITLE
`@hasSection`/`@sectionMissing` uses `@else`, and `@endif` as closing

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#19]
`@hasSection` and `sectionMissing` uses `@endif` as closing, also they can use **`@else`**

https://laravel.com/docs/9.x/blade#section-directives

I get `Blade Sintax Error Unexpected @endif After T_BLADE_CLOSE_ECHO`

Example:
```blade
@hasSection('navigation')
    
@endif

@sectionMissing('navigation')
    
@endif
```
![image](https://user-images.githubusercontent.com/109294935/185170525-5d5bc5de-533d-45f2-8eb9-8cda2539841a.png)

**Comment by haidubogdan** [comment]
Sorry for the bug.
I've pushed a fix in the a new release https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb-122-126-18082022

**Comment by parallels999** [comment]
Thanks
