### ISSUE TITLE
First and Fourth argument of `@each` directive are a path

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#22]
https://laravel.com/docs/9.x/blade#rendering-views-for-collections
```blade 
@each('view.name', $jobs, 'job', 'view.empty')
```

**Comment by haidubogdan** [comment]
Hi,

Thank you for you observation.
For the moment I've just added the autocomplete of the first blade path and the declaration finder.

[](https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb-122-126-18082022-v2)

We will keep the issue opened until a valid parser is added for this directive and the fourth parameter is seen as a view path.

**Comment by parallels999** [comment]
Thanks 👍

**Comment by parallels999** [comment]
Hi
Also `@includeWhen`, `@includeUnless` has path on second argument, 
and `@includeFirst` has an array of paths on first

```blade
@includeWhen($boolean, 'view.name', ['status' => 'complete'])
 
@includeUnless($boolean, 'view.name', ['status' => 'complete'])

@includeFirst(['custom.admin', 'admin'], ['status' => 'complete'])
```

**Comment by parallels999** [comment]
Thanks
