### ISSUE TITLE
Blade directives break javascript highlighting after use them on comments

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#23]
Seems a small thing, but it is strange to me, maybe a bug

**Example Blade Markdown:**
```blade
<script>
var test1 = 'test';
/*@test('test')*/
var test2 = 'test';
function test(data) {}
if (test2) {}
</script>
```
**Netbeans:** After comment, highlighting stops working
![image](https://user-images.githubusercontent.com/109294935/185632898-29555515-c316-4f07-8ef8-6bfc974f5c6b.png)

**Comment by haidubogdan** [comment]
ok, good observation. Thank you.

**Comment by parallels999** [comment]
It seems fixed on the last release, thanks
