### ISSUE TITLE
[BUG] Blade autocomplete break **CTRL + Z** when custom blade directives

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#24]
Custom blade directives are added on `Project Properties` -> `Blade Directives`

**Steps to Reproduce:**

Just write anything, and use `Blade Autocomplete` for any custom blade directive, 
after text autocomplete try `CTRL + Z` for undo everything, 
it doesn't works anymore, you can't undo the directive and the first writing

With the Laravel oficial blade directives `CTRL + Z` works

**NOTE:** I'm trying with 
[spatie/laravel-permission/src/PermissionServiceProvider.php#L103-L110](https://github.com/spatie/laravel-permission/blob/dbc6c18ef4b2d097350a5faf82382564748e6c97/src/PermissionServiceProvider.php#L103-L110), 
[spatie/laravel-blade-javascript/src/BladeJavaScriptServiceProvider.php#L21-L25](https://github.com/spatie/laravel-blade-javascript/blob/a509ab5bc15bfc413c538b74d9666369985fe502/src/BladeJavaScriptServiceProvider.php#L21-L25)
[spatie/laravel-honeypot/src/HoneypotServiceProvider.php#L45-L47](https://github.com/spatie/laravel-honeypot/blob/181e385ca367de6da7223e82e61fc50ee1c60ab9/src/HoneypotServiceProvider.php#L45-L47)

**Comment by haidubogdan** [comment]
Sorry I can't reproduce the bug.

When you have this issue can you look at the bottom of the screen for a error balloon and do a printscreen with a detail info?

![image](https://user-images.githubusercontent.com/15365717/189470381-fd1f5c49-1d7f-4770-a387-d876436345ea.png)

It might be some netbeans cache data corruption also.
you can try the following things
- remove the files from the BladeDirective configuration
- close the project
- and open the project again and try to add the files back

Please tell me if this still happens and I will try to check for possible file reference errors.

**Comment by parallels999** [comment]
I already try that and it give me the same result
I am using **Netbeans 14**
Also, I noticed that after using `CTRL + Z` between 30 and 80 times, it start the `undo` action again

**Comment by haidubogdan** [comment]
It's strange I still can't reproduce the bug, and in a way the error doesn't make sense without a error notification from netbeans. Before preparing to add just a small validation.
Can you check if the bug will be reproduced 
You should have the following file
{YourProject}/nbproject/private/private.properties

![image](https://user-images.githubusercontent.com/15365717/189713245-906635ea-040a-4da1-bd99-6d129ae3092e.png)

Try to empty the config for complier like

```
auxiliary.php-blade.compiler_2e_path_2e_list=
```
Now try to add again the provider files for the custom directives and check if the bug still occurs

**Comment by parallels999** [comment]
it still happens

Before
![image](https://user-images.githubusercontent.com/109294935/189715047-d7fda8d9-399f-40cb-986a-555d1f06fe7b.png)
After
![image](https://user-images.githubusercontent.com/109294935/189715472-fe64f451-a861-43b3-8202-b602cf01201c.png)

**Comment by parallels999** [comment]
I tried installing netbeans 12.5 and in this version it seems to work correctly

**Comment by parallels999** [comment]
i did upgrade to netbeans 15, and everything works, thanks for your time

**Comment by haidubogdan** [comment]
Good news :) .
I'm using netbeans 14 also, and didn't encountered problem.
I presume that it can be related to additional installed plugin as it looks to be a typehook issue.
