### ISSUE TITLE
[BUG] On blade comments

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#27]
I'm trying to write `{{-- --}}`, but it only writes `{{-`
So i try to copy/paste `{{--` and then netbeans freezes, it needs a restart

**Netbeans Version:** 16
**Plugin Version:** php-blade-14102022.nbm

**Comment by haidubogdan** [comment]
Hi, I didn't encountered the issue so far on my computer. 
But as I worked on some refactoring I didn't push new code and updates for a long time.
I hope the new version https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/php-blade-122-126-03032023
will help.

**Comment by parallels999** [comment]
It is working now, thanks
