### ISSUE TITLE
Code highlighting | Namespace import

### ISSUE THREAD

**Issue by wimurk** [haidubogdan/netbeans-php-blade-plugin#28]
### First of all, this plugins is amazing!

Thanks for all the work guys. This plugin really helps with developing in laravel.
I tested it in Netbeans 17 and it works great. 

besides that is works great here are a few options that can be fixed in the next verisons.

### Namespace use statements
When importing classes using the `use` the editor does not bind the classes you import. (No typehinting etc)
Also the editor does not register the imported class as being used.

<img width="333" alt="image" src="https://user-images.githubusercontent.com/14072334/224963312-23c35a5d-85cb-48a8-86ef-12c30cb4693a.png">

### shorthand if statement
When using the <condition> ? <value> : <value> the highlighting does't work anymore.
<img width="312" alt="image" src="https://user-images.githubusercontent.com/14072334/224963911-b59b5fff-220a-4be4-9df1-7b88cca8fd97.png">

**Comment by haidubogdan** [comment]
Hi wimurk, thanks for the observation. 
I agree, these are things which need to improve.
External language embedding can be a challenge when implementing custom plugins, but I think it can be doable in the future.
For the second issue ... there is a problem with Netbeans Ide freezing in some context when typing "::", so I added some harsh embedding limitations . I think this shorthand if statement is fixable, also;

**Comment by parallels999** [comment]
> When importing classes using the use the editor does not bind the classes you import.

Yes, but normally you shouldn't do that (good practice), you should use view composer, or use `User::first()` in the controller and send it to the view

Also you could simple do:
```php
<?php
use App\Models\User;
?>
```

**Comment by wimurk** [comment]
> > When importing classes using the use the editor does not bind the classes you import.
> 
> Yes, but normally you shouldn't do that (good practice), you should use view composer, or use `User::first()` in the controller and send it to the view
> 
> Also you could simple do:
> 
> ```
> <?php
> use App\Models\User;
> ?>
> ```

Yes, this was an example. Most of the times i have services that i use in my blade to process some data information. 
Have you guys already looked into the code formtting? Myself i use the psr12 provided by pint (default laravel). This sometimes gives weird markup in combination with <x- components. Might be an issue with netbeans itself tho.

**Comment by haidubogdan** [comment]
I will close the ticket as the plugin has changed a lot.
Currently there is no Warning notice inside `@php` directive for unused Use Statement.
