### ISSUE TITLE
Highlight error when string `:` on arguments

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#29]
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/109294935/2189e089-f5b5-4d3e-adb4-321bc4ba4f4e)

```blade
    @test('test:test')
    @test('test&test')
    @test('test_test')
```

**Comment by parallels999** [comment]
Now it is worst, it freezes after typing `:`

**Comment by haidubogdan** [comment]
I'm sorry for that, can you give me a sample of syntax which trigger a freeze ?

**Comment by parallels999** [comment]
```blade
@test('test::test')
```

**Comment by haidubogdan** [comment]
It's strange, I don't have this issue on my computer.
I will try to install the release plugin it on a different environment to see if it crashes.

**Comment by parallels999** [comment]
ok, I'll try to do other tests with the latest version

**Comment by parallels999** [comment]
try writing letter by letter this:
```blade
@test(["test":"test"])
```
Before the problem was only highlight of `@test('test:test')`, now it freezes netbeans

**Comment by haidubogdan** [comment]
Got it ... 
I could reproduce the freeze of the IDE on @test(["test": .
But it seems to appear on the previous version 1.0.0.47 also.

Yet, I could not reproduce a freeze for @test('test:test') with version 1.0.0.47 and 1.0.0.50 .

If you remember  the last stable a previous version, you can try to uninstall the plugin and install from the list of releases : https://github.com/haidubogdan/netbeans-php-blade-plugin/tags.

**Comment by parallels999** [comment]
> I could not reproduce a freeze for @test('test:test') with version 1.0.0.47 and 1.0.0.50

It never freeze with `@test('test:test')`, it was only highlight problem

**Comment by parallels999** [comment]
In the lastest version a strange behavior returned in case of the colon
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/109294935/850077e8-7d4b-4d4c-b55a-267c00b2e605)
```blade
@test(session('status')===true?'test':'test2')
@test(session('status')===true ? 'test' : 'test2')
```

**Comment by haidubogdan** [comment]
Sorry ... it's still the embedding php freeze issue

**Comment by parallels999** [comment]
No, code highlight problem after after using `:`

**Comment by parallels999** [comment]
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/109294935/ba001825-87da-4a93-871f-778cd5d9cb54)
```blade
@test("{hiddentrue}")
@test("{hidden:true}")
@test("{hidden:true}")
```

**Comment by haidubogdan** [comment]
Yes, unfortunatelly
I've published a new release, I hope this version will more stable.

I didn't created a ticket for apache/netbeans developer team, and I think they have enough issues to fix :) .
As this is a more like a plugin which uses apache/netbeans php embedding, it might be difficult to find the freeze issue.

**Comment by parallels999** [comment]
>I hope this version will more stable.

Seems more stable, but
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/109294935/be02dc70-6d8c-407b-9d11-36400d4b8fea)
```blade
@test("{hiddentrue}")
@test("{hidden:true}")
@test("{hidden:true}")
@test("{name:'imag_id',hidden:true},", true, 'string', ['array'])
```

**Comment by parallels999** [comment]
Great work, thank you very much ❤️🚀
