### ISSUE TITLE
Blade Sintax Error, Unexpected T_BLADE_CLOSE_ECHO

### ISSUE THREAD

**Issue by systemsolutionweb** [haidubogdan/netbeans-php-blade-plugin#3]
I get `Blade Sintax Error, Unexpected T_BLADE_CLOSE_ECHO` if i do this
```html
<script>
var a={a:{}};
</script>
```

**Comment by haidubogdan** [comment]
Hi thank you for the observation.
I've pushed a new commit with the fixes for this issue.
and I've also created a pre-release : https://github.com/haidubogdan/netbeans-php-blade-plugin/releases

**Comment by erikn69** [comment]
+1

**Comment by haidubogdan** [comment]
I've pushed a new release. Hope the issue will be fixed
https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb122-126-03032022

**Comment by systemsolutionweb** [comment]
Fixed
