### ISSUE TITLE
@if formatting is not working

### ISSUE THREAD

**Issue by Eugene-Melbourne** [haidubogdan/netbeans-php-blade-plugin#33]
@if formatting is not working

actual formatting 

```
        @if ($params->allow_google_in_country)
        <div class="form-group row">
            aaa
        </div>
        @endIf
```

expected formatting

```
        @if ($params->allow_google_in_country)
            <div class="form-group row">
                aaa
            </div>
        @endIf
```

**Comment by haidubogdan** [comment]
The formatting and indentation for blade code is a feature which is in work in progress.
It is not working yet.

**Comment by haidubogdan** [comment]
Hi,

With the release of https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb180-v2.1.21

I've added the formatting action. But you will have to enable it manually for the moment.

![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/15365717/8a44ac46-24e6-48ad-83e2-52a89ec0b3bf)

**Comment by haidubogdan** [comment]
v 2.1.21 still has some fornatting issues, do I recommend waiting for a later release .

**Comment by haidubogdan** [comment]
I've fixed the relevant issues so https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb180-v.2.1.3
Can be tested for the formatting flows.

**Comment by wimurk** [comment]
I just downloaded the latest release and tested with a simple blade

```html
<x-base::layouts.app>
    <div class="max-w-9xl mx-auto px-4 sm:px-6 md:px-8">
        @include('base::components.breadcrumbs')

        <div class="mt-2 md:flex md:items-center md:justify-between">
            <div class="flex-1 min-w-0">
                <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                    {{ __('invoices::collection-invoices.index.Collection invoices') }}
                </h2>
            </div>
        </div>
    </div>

    <div class="max-w-9xl mx-auto px-4 sm:px-6 md:px-8 py-5">
        <div class="p-6 bg-white border-b border-gray-200 shadow-sm rounded-md">
            <livewire:invoices::collection-invoice-table />
        </div>
    </div>
</x-base::layouts.app>
```

After formatting `CTRL + SHIFT + F`
```html
<x-base::layouts.app>
    <div class="max-w-9xl mx-auto px-4 sm:px-6 md:px-8">
        @include('base::components.breadcrumbs')

        <div class="mt-2 md:flex md:items-center md:justify-between">
            <div class="flex-1 min-w-0">
                <h2 class="text-2xl font-bold leading-7 text-gray-900 sm:text-3xl sm:truncate">
                    {{ __('invoices::collection-invoices.index.Collection invoices') }}
                </h2>
            </div>
        </div>
    </div>

    <div class="max-w-9xl mx-auto px-4 sm:px-6 md:px-8 py-5">
        <div class="p-6 bg-white border-b border-gray-200 shadow-sm rounded-md">
                                                        <livewire:invoices::collection-invoice-table />
        </div>
    </div>
                                                </x-base::layouts.app>
```

# Test number 2
Openend somewhat bigger blade
Without formatting the blade looks like this
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/14072334/f182d24f-f277-452b-957e-bec7e78d3db4)

When removing the @foreach
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/14072334/7b9cc02e-1fb5-4c0b-b9b2-14cbf05a7fbe)

**Comment by wimurk** [comment]
> So many new stuff : )
> 
> I will prepare a fix for the formatting issue.
> 
> And it seems I have I to take care about components include in the future
> 
> ```
> @include('base::components.breadcrumbs')
> ```

You know you are the life saver of netbeans and laravel! Great work.

**Comment by haidubogdan** [comment]
I will put it on `in progress` as it's a bit "wonky".

Some existing issues:
- `Ctrl-Z` is resetting each last format step by step
- some tags are still not indented well

**Comment by haidubogdan** [comment]
Closing this issue, some progress have been done, and new separate issues have been opened for other formatting errors.
