### ISSUE TITLE
`unknown directive` on custom blade directives

### ISSUE THREAD

**Issue by angeljqv** [haidubogdan/netbeans-php-blade-plugin#34]
- #8
In my previous issue you added the functionality to autocomplete the blade directives(_custom/3rd party_), in version 2, it still works but it marks them as `unknown directive`, but if they are added for autocompletion they should be known, or am i missing something?
**This leaves too many messages in all my documents, it's harder to focus on the messages that really matter.**

**Comment by haidubogdan** [comment]
It's strange if the blade is added in autocompletion It should be considered a custom directive.

You can try to re-add the service provider class where you define the blade directives with 
Project -> Properties -> Laravel Blade -> Custom Directives

---
The current system is designed that on Ctrl+Click over a custom directive to go the the Service Provider Class where the custom directive was defined.

**Comment by angeljqv** [comment]
From [spatie/laravel-permission/src/PermissionServiceProvider.php#L129-L138](https://github.com/spatie/laravel-permission/blob/e4fd5ca7be0d7f7654c1151ff3614eb28c3a19a9/src/PermissionServiceProvider.php#L129-L138)
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/7b9b35cd-9a60-4332-89b1-7b4ffc0d2960)
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/d92c9093-19e3-46b3-a462-1e48e8b2b7da)

I already tried to add the service provider again, I also tried to clear the entire cache, I am using Netbeans 19

--- 
>The current system is designed that on Ctrl+Click over a custom directive to go the the Service Provider Class where the custom directive was defined.

I didn't know it, `Ctrl + Click` does exactly what you say, open the service provider

---
>Maybe it is not possible, but what about this idea
>
>It doesn't work with relative paths
Files with custom directives always are inside project root path, so, we can use relative paths instead of absolute paths(same with views path)
>
>After that, what if instead of saving in private.properties it save it in project.properties, so it could be on the repository tree,
everyone with the plugin could use custom directives autocompletion automatically

**Comment by angeljqv** [comment]
There is no way to disable that message
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/e178f8aa-ff1d-4c6c-810c-c1be8969a34c)

**Comment by angeljqv** [comment]
I updated to a newer netbeans, the message disappeared, but there is a strange underline

![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/20a2f58a-03ee-4f0e-9004-6adb1d344140)

**Comment by haidubogdan** [comment]
cool, this is just to have a soft identification that it is a custom directive.

**Comment by angeljqv** [comment]
I have these 3 custom directives
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/41bb4bb6-c8ab-400c-8355-57b16bcc56fe)

![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/44dfed02-4b5d-44a6-9122-4c922f4c8b4e)
`@card` like no blade directive, `@cardTitle` strange underline, and `@endcard` is fine

If i remove `@cardTitle` args
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/a3d5b138-5b98-4d4b-8105-c4e9e8e9a556)

**Comment by parallels999** [comment]
>`@card` like no blade directive, `@cardTitle` strange underline, and `@endcard` is fine
>If i remove `@cardTitle` args, no more blade directive
>If i add `( )`, `@card` starts working, maybe related to https://github.com/haidubogdan/netbeans-php-blade-plugin/issues/37

+1

**Comment by haidubogdan** [comment]
For the moment I've prepared a pre-release to recognize custom directives whiteout arguments

https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb180-v.2.0.7-pre .

There are some things which are still work in progress

**Comment by haidubogdan** [comment]
Closing the ticket.
From v.2.1.21 there is the option to disable these types of warnings : 

Editor -> Hints -> Language Blade :

![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/15365717/8b10a93e-23fa-4f01-9f26-d664248ba1c3)

**Comment by josevv28** [comment]
>It doesn't work with relative paths
Files with custom directives always are inside project root path, so, we can use relative paths instead of absolute paths(same with views path)
>
>After that, what if instead of saving in private.properties it save it in project.properties, so it could be on the repository tree,
everyone with the plugin could use custom directives autocompletion automatically

Sounds like a great idea

**Comment by angeljqv** [comment]
Hi @haidubogdan, the problem is back, There should not be any type of tests to prevent already solved bugs from returning.

![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/da573afa-2259-43a7-988a-e2787e15397f)
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/5f076c26-f88d-4f2b-9831-0c06b8a99418)
```blade
@card
  @cardTitle([
```

___

> I have these 3 custom directives 
![image](https://private-user-images.githubusercontent.com/79208641/311354798-41bb4bb6-c8ab-400c-8355-57b16bcc56fe.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzc0NDIsIm5iZiI6MTcxMjA3NzE0MiwicGF0aCI6Ii83OTIwODY0MS8zMTEzNTQ3OTgtNDFiYjRiYjYtYzhhYi00MDBjLTgzNTUtNTdiMTZiY2M1NmZlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE2NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTY5MmVjOGYxOWVmNmY5NmJhNmEzMDMxNjA1NmY4YzRiYzIyMDA1ZTRkMTZjYzZmMzFkZjRiZTcyNGYyNzJkYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.TkfWE_WyaQzV1jPhC4a63VBuWtUZVZUJOYzrF5uEjm8)
> 
> ![image](https://private-user-images.githubusercontent.com/79208641/311355035-44dfed02-4b5d-44a6-9122-4c922f4c8b4e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzc0NDIsIm5iZiI6MTcxMjA3NzE0MiwicGF0aCI6Ii83OTIwODY0MS8zMTEzNTUwMzUtNDRkZmVkMDItNGI1ZC00NGE2LTkxMjItNGM5MjJmNGM4YjRlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE2NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTlmYjU0NDBmNzBiOWY3Y2YyOWZmZmYxMTUwNDY1OTgyZDI1ZjRkZGI4YTIzMTFlODc0YmM5MzFkZjQyN2MxMWYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.6mmTKS-Xa8BVvRglCPNh68-cFhO6GBSZ2JXcI7BUlyU) 
>`@card` like no blade directive, `@cardTitle` strange underline, and `@endcard` is fine
> 
> If i remove `@cardTitle` args, no more blade directive 
![image](https://private-user-images.githubusercontent.com/79208641/311355529-a3d5b138-5b98-4d4b-8105-c4e9e8e9a556.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzc0NDIsIm5iZiI6MTcxMjA3NzE0MiwicGF0aCI6Ii83OTIwODY0MS8zMTEzNTU1MjktYTNkNWIxMzgtNWI5OC00ZDRiLTgxMDUtYzRlOWU4ZTlhNTU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE2NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMzMDRhYjA3NDA3NDczODRjYzY3YzY2NWM4MGU4MTdiNjhjNmVjMzYzY2IzYmNjYmE1ODgzZjAwYWFhYTA5MjEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.RNJKBBdiRVqT4Q0ntcJ129Ao2pCO0Q4zjYvsgyKG1Q8)
> 
> If i add `()`, `@card` starts working, maybe related to #37 
![image](https://private-user-images.githubusercontent.com/79208641/311357972-8b1d29fc-c9ff-46da-a3a2-33ea8f858614.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzc0NDIsIm5iZiI6MTcxMjA3NzE0MiwicGF0aCI6Ii83OTIwODY0MS8zMTEzNTc5NzItOGIxZDI5ZmMtYzlmZi00NmRhLWEzYTItMzNlYThmODU4NjE0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE2NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTI3MGJkZmQxODViYjg4MTJhMzk0MmIxZTMyMTg1MDU4YmFhYzdiOTRkMTNkZGM1MWY4YjJhZWNkODIzNDcxOTImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.GSnxUNFPE1yY_RkdDxPq1kW1ppVaebwnamI7Z5wxWmU)
> 
> ![image](https://private-user-images.githubusercontent.com/79208641/311357524-a9f99c5b-2638-40f3-86ce-9890aebe2451.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIwNzc0NDIsIm5iZiI6MTcxMjA3NzE0MiwicGF0aCI6Ii83OTIwODY0MS8zMTEzNTc1MjQtYTlmOTljNWItMjYzOC00MGYzLTg2Y2UtOTg5MGFlYmUyNDUxLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDAyVDE2NTkwMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZiZmFhMTEyNjAzZTY0ZTA2YjQzM2ExZDdiODcyZmQ4YmQyOTNkY2M4M2ExNDRjNTE0YjU2NzVkN2ZjZTgzZGQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.jqFxDqm8KHfkl4Q67fTSIgf750aHeDiNLKLDalg18D4)

**Comment by haidubogdan** [comment]
Hi,
 you are right, some tests should be implemented in the future.

**Comment by angeljqv** [comment]
It works again, thanks
