### ISSUE TITLE
`Unclosed @if` when `@endif` exists

### ISSUE THREAD

**Issue by angeljqv** [haidubogdan/netbeans-php-blade-plugin#36]
Try this, but separately, imagine that they are inside some loop
```blade
@if(true) @continue @endif

@if(true) @break @endif

@if(true) 
    @break @endif

@if(true) 
    @continue @endif
```

**Comment by haidubogdan** [comment]
It was interesting case.
`@continue` and `@break` can also take parameters and the parser didn't treat an inline use case correctly.
It should be fixed with : https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb180-v.2.0.6
