### ISSUE TITLE
No highlight open tags `@canany`/`@endcanany` when selecting end tags

### ISSUE THREAD

**Issue by angeljqv** [haidubogdan/netbeans-php-blade-plugin#38]
~`@can`/`@canany` are laravel core but shows `unknown directive`,~ **Fix on v2.0.5**
~also no highlight tags, if you select open/close `canany`, the counterpart is not highlighted, it is difficult to find where the block starts/ends~
On `can`/`@canany` not works highlight on selecting end tag

![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/72e213f5-fc4d-49ae-a693-8fa39ab05312)

```blade
@canany([''])

@endcanany

@can('')

@endcan
```

**Comment by haidubogdan** [comment]
- should be fixed from release 2.0.5
