### ISSUE TITLE
Custom `@end` prefix tag could have arguments, and if they start witn `end` stops highlight

### ISSUE THREAD

**Issue by angeljqv** [haidubogdan/netbeans-php-blade-plugin#39]
I have custom blade directives, coincidentally they start with `end`, and the highlighting of the arguments does not work

![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/79208641/8c5006ba-a1e8-4377-ab72-397dce72615b)
```blade
  @modal(['id'=>'ModalFirmaElectCheck'])

  @endmodal(['cancel' => true])
  
  @endorse(['save' => true])
  
  @endpoint('custom_value')
```

**Comment by haidubogdan** [comment]
I've added a quick fix for the php highlight and a logic to detect custom directive blocks.

But I think the ticket can be left opened.

https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb180-v.2.0.6

**Comment by haidubogdan** [comment]
I will close the ticket.
Starting from v.2.1.21.

You can also disable the hints from Editor -> Hints -> Language Blade

![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/15365717/c6a09416-0cb2-4a37-9f17-06c8390688b9)
