### ISSUE TITLE
`extraneous input <EOF>` in a correct blade file

### ISSUE THREAD

**Issue by angeljqv** [haidubogdan/netbeans-php-blade-plugin#40]
Create a new blade file, and just write
```blade
<?php
// nothing or write any PHP statement
```
When is executed everything works correctly, but the model shows it as an error

**Comment by haidubogdan** [comment]
It should be fixed with : 
https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb180-v.2.0.6
