### ISSUE TITLE
Weird highlight on double quotes

### ISSUE THREAD

**Issue by parallels999** [haidubogdan/netbeans-php-blade-plugin#49]
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/109294935/7c8effc5-8d39-4d39-81b8-ef22eb03bc75)

```blade
@blade(['key' => "value"])
```

**Comment by haidubogdan** [comment]
I've did a revert on v.2.1.80, but with a small change on the lexer I hope #25 is still fixed

**Comment by parallels999** [comment]
I don't know if it is my netbeans that is causing problems.
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/109294935/144d2705-5edc-4a87-80b9-31fddb960b7d)

**Comment by haidubogdan** [comment]
Sorry ... it might be a refactor bug

**Comment by parallels999** [comment]
Something is not working on v.2.1.80, reverting to v.2.1.70
I don't go beyond `Background Scanning Proyects...`

**Comment by haidubogdan** [comment]
I had a similar thing also ... after a computer reboot, the Project scanning finished successfully.
Indeed there is some kind of Memory / Thread leak, which can be researched and maybe it is also IDE related.

**Comment by parallels999** [comment]
Also freezes when adding custom blade directive files

**Comment by haidubogdan** [comment]
Sorry, for the inconvenience . I've published v.2.2.1.2 version in which I try to optimize this. It is still a work in progress.

**Comment by parallels999** [comment]
```blade
<style>
    @media(min-width:992px){
       .test{margin-left:0px;}
    }
</style>
```
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/109294935/3cd788e1-d12d-4a6e-b5ae-8a573f5bb4fb)

**Comment by parallels999** [comment]
The latest version looks more stable, 
but when there are more than one custom blade directive file, it only takes into account the last file, the ones before this are not added to the syntax
