### ISSUE TITLE
improve formatting

### ISSUE THREAD

**Issue by haidubogdan** [haidubogdan/netbeans-php-blade-plugin#57]

**Comment by wimurk** [comment]
Hello @haidubogdan i noticed a bug in the formatting

When you use a select input and add `<optgroup>`  the formatting breaks
How it should look
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/14072334/4b504032-50f7-43fd-9096-a49ea1383c9d)

After formatting
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/14072334/d6914481-6956-4427-bcbb-8fcb3af77be4)

Notice the formatting after the ` <opgroup ...` it ignores the that additional tab.

**Comment by haidubogdan** [comment]
Hi,
thank you for the observation.
It seems `<optgroup>` tag was missing from the formatting rule.
I've prepared the fix in a pre-release version : https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/prenbpr1.0.3 .

**Comment by haidubogdan** [comment]
Closing, 
Will try to switch to exact examples of formatting issues to fix.
The latest releases > [2.4.9.6](https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/prenbpr1.0.5)  should have the formatting of :  

```
@section('id')
    <div>
        <x-card>
            <livewire:products-table/>
        </x-card>
    </div>
@endsection
```

working.
