### ISSUE TITLE
Wrong font color on dark themes

### ISSUE THREAD

**Issue by erikn69** [haidubogdan/netbeans-php-blade-plugin#6]
Can't read hints due to font color on dark themes

![image](https://user-images.githubusercontent.com/4933954/156443504-e8c712bd-150e-4cc3-b45f-7a7d8d6e714f.png)

![image](https://user-images.githubusercontent.com/4933954/156442978-468db45e-19ba-499b-a9d2-a7c7efd6f5c5.png)

**Comment by haidubogdan** [comment]
can you give me the name of the theme, please, to see if there is a way to autodetect the color which is used.

**Comment by haidubogdan** [comment]
Sorry I closed the issue by mistake.
Can you do a test with the latest npm update ? 
https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nb122-126-03032022

You will have to uninstall the existing plugin and from downloads the plugin which appears is usually cached so you have to remove it.

**Comment by erikn69** [comment]
Thanks, it is working now

The theme was **FlatLaf Dark**
