### ISSUE TITLE
Breaks Javascript highlighting 

### ISSUE THREAD

**Issue by cesarreyes3** [haidubogdan/netbeans-php-blade-plugin#61]
![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/109559100/0b2312e0-410b-4d91-869a-e00bff982642)

```blade
<script>
/*@can('test')*/
console.log('test');
/*@endcan*/
console.log('test2');
</script>
```

**Comment by haidubogdan** [comment]
Hi,
Thank you for the observation.
I did a new release version [2.4.8.8](https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nbpr1.0.5) which should fix this issue.

**Comment by cesarreyes3** [comment]
Thanks 👍
