### ISSUE TITLE
Slash comments in embeded style tags display parser error

### ISSUE THREAD

**Issue by haidubogdan** [haidubogdan/netbeans-php-blade-plugin#63]
```
<style>
    //dsdsds ?
</style>
```

![image](https://github.com/haidubogdan/netbeans-php-blade-plugin/assets/15365717/3a32ed5b-e873-4ffb-be89-fd865d78360d)

**Comment by parallels999** [comment]
https://developer.mozilla.org/en-US/docs/Web/CSS/Comments

I thought you could only comment with `/*   */`

**Comment by parallels999** [comment]
Tested

**Comment by haidubogdan** [comment]
Ah yes : ))
I thought it's more permissive.
