### ISSUE TITLE
Blade echo breaks html highlight on ternary operator

### ISSUE THREAD

**Issue by angeljqv** [haidubogdan/netbeans-php-blade-plugin#66]
Hi, this seems like a highlight bug

![image](https://github.com/user-attachments/assets/dbd87abc-bff6-4147-9852-8672f5ec87fc)

```blade
<select>
    <option {{ $MyFlag?"disabled=''":'' }}>My Option</option>
</select>
<div>My Html</div>
<input type="text" />
```
Great plugin by the way

**Comment by haidubogdan** [comment]
Thanks for the feedback :) .
"Unfortunately" I can't reproduce it with my latest release version https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/nbpr1.0.8 [2.5.0.0] .

I've added the new version on netbeans plugin repository, and I hope that in two or three weeks it will be validated.

https://plugins.netbeans.apache.org/catalogue/?id=100

![image](https://github.com/user-attachments/assets/da3d37e8-e3be-4a65-af50-46b7e706ddf1)

**Comment by angeljqv** [comment]
![image](https://github.com/user-attachments/assets/ced21f91-8628-48de-8d5b-cb86675e6028)
![image](https://github.com/user-attachments/assets/559c7ec5-2369-4cf7-941b-8502d74bfc39)

**Comment by haidubogdan** [comment]
ok I will see with netbeans 21.
Maybe it's also a case of carriage return "\r\n"

**Comment by angeljqv** [comment]
I think I managed to make it easier to reproduce.


```blade
    <select>
        <option {{ $MyFlag?"disabled=''":'' }}>My Option</option>
    </select>
    <div>My Html</div>
    <input type="text" />
```
look the bug
![image](https://github.com/user-attachments/assets/dbd87abc-bff6-4147-9852-8672f5ec87fc)

Then remove `"` on input(`type="text"`)
![image](https://github.com/user-attachments/assets/d32e889e-a86d-4c03-bca5-b1b8d865374a)




----
Unix LF ![image](https://github.com/user-attachments/assets/a6bdab4a-8610-415b-b467-c6531a33a9f9)

**Comment by haidubogdan** [comment]
I reproduced it by adding <input type="text" />
I will see what can be done.

**Comment by haidubogdan** [comment]
To adjust for the moment I see that adding spaces between "?" will bypass the bug.

```
<select>
    <option {{ $MyFlag ? "disabled=''":'' }}>My Option</option>
</select>
<div>My Html</div>
<input type="text" />
```

**Comment by angeljqv** [comment]
>  I see that adding spaces between "?" will bypass the bug.

I already knew that, but that wouldn't be the point

Other ways, like exchanging the type of quotes
![image](https://github.com/user-attachments/assets/e2bc0a4b-f8dc-40de-a392-ba705a3f777e)

**Comment by haidubogdan** [comment]
I've prepared a fix in a prerelease 
https://github.com/haidubogdan/netbeans-php-blade-plugin/releases/tag/prenbpr1.0.8

I will need some time to test it.

**Comment by angeljqv** [comment]
thank you 👍👍
