### ISSUE TITLE
Missing `@when`, `@bool` blade directives

### ISSUE THREAD

**Issue by angeljqv** [haidubogdan/netbeans-php-blade-plugin#72]
`@when` could be useful for conditionally printing things in general
```blade
<input name="phone" @when($isRequired, 'required') />
```

`@bool` allow boolean values to be printed directly into strings or used in object construction.
```blade
<script>
    let config = {
        isActive: @bool($isActive),
        hasAccess: @bool($hasAccess)
    };
</script>
```

**Comment by haidubogdan** [comment]
Interesting, this is new.

I didn't find these in their library.

Maybe it's a third party plugin which I'm missing?

**Comment by angeljqv** [comment]
- `@when` https://github.com/laravel/framework/pull/52665
- `@bool` https://github.com/laravel/framework/pull/53179
